version: "3.9"

services:
  movie-backend:
    build:
      context: ./backend
    environment:
      - ECR_REGISTRY=$ECR_REGISTRY
    image: ${ECR_REGISTRY}/movie-backend:${BE_IMAGE_TAG}
    ports:
      - "5000:5000"
    restart: unless-stopped

  movie-frontend:
    build:
      context: ./frontend
    environment:
      - ECR_REGISTRY=$ECR_REGISTRY
    image: ${ECR_REGISTRY}/movie-frontend:${FE_IMAGE_TAG}
    ports:
      - "3000:3000"
    restart: unless-stopped
