name: Backend CD Pipeline

on:
  push:
    branches:
      - "master"
    paths:
      - "backend/**"
  workflow_dispatch:

defaults:
  run:
    working-directory: ./backend

jobs:
  backend-ci:
    uses: ./.github/workflows/backend-ci.yml

  deploy:
    runs-on: "ubuntu-22.04"
    environment: dev
    # do not run on PRs
    needs: [ backend-ci ]

    steps:
      - name: Clone the repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region ${{ vars.AWS_DEFAULT_REGION }} --name ${{ vars.CLUSTER_NAME }}

      - name: Kustomize set image
        working-directory: backend/k8s
        run: |
          kustomize edit set image backend=${{ vars.ECR_REGISTRY }}/movie-backend:${{ github.sha }}

      - name: Deploy application to EKS cluster
        working-directory: backend/k8s
        run: |
          kustomize build . | kubectl apply -f -

      - name: Verify deployment
        run: |
          if kubectl rollout status deployment/backend | grep -q 'successfully rolled out'; then
            echo "Backend deployment succeeded."
          else
            echo "Backend deployment failed."
            exit 1
          fi
