name: Backend CI Pipeline

on:
  pull_request:
    branches:
      - "master"
    paths:
      - "backend/**"
  workflow_call:

defaults:
  run:
    working-directory: ./backend

jobs:
  lint:
    runs-on: "ubuntu-22.04"

    steps:
      - name: Clone the repo
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pipenv flake8
          pipenv install

      - name: Run Linting
        run: |
          pipenv run lint

  test:
    runs-on: "ubuntu-22.04"

    steps:
      - name: Clone the repo
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install

      - name: Run Tests
        run: |
          pipenv run test
