name: Frontend CD Pipeline

on:
  workflow_run:
    workflows: ["Frontend CI Pipeline"]
    type:
      - completed

defaults:
  run:
    working-directory: ./frontend

jobs:
  build:
    # check if workflow is started manually or the previous workflow succeeded
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: "ubuntu-22.04"
    environment: dev

    steps:
      - name: Clone the repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          # role-to-assume: github-action-user

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'

      - name: Build and push docker image to Amazon ECR
        run: |
          export ECR_REGISTRY=${{ vars.ECR_REGISTRY }}

          export FE_IMAGE_TAG=${{ github.sha }}
          docker-compose build movie-frontend
          docker-compose push movie-frontend

          export FE_IMAGE_TAG="latest"
          docker-compose build movie-frontend
          docker-compose push movie-frontend

  deploy:
    runs-on: "ubuntu-22.04"
    environment: dev
    needs: build

    steps:
      - name: Clone the repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          # role-to-assume: github-action-user

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region ${{ secrets.AWS_DEFAULT_REGION }} --name ${{ vars.CLUSTER_NAME }}

      - name: Kustomize set image
        working-directory: frontend/k8s
        run: |
          kustomize edit set image frontend=${{ vars.ECR_REGISTRY }}/movie-frontend:latest

      - name: Deploy application to EKS cluster
        working-directory: frontend/k8s
        run: |
          kustomize build . | kubectl apply -f -

      - name: Verify Deployment Status
        run: |
          if kubectl rollout status deployment/frontend | grep -q 'successfully rolled out'; then
            echo "Deployment succeeded."
          else
            echo "Deployment failed."
            exit 1
          fi
