name: Frontend Pipeline

on:
  push:
    branches:
      - 'master'
    paths:
      - 'frontend/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./frontend

jobs:
  lint:
    if: False
    runs-on: "ubuntu-22.04"

    steps:
      - name: Clone the repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache dependencies
        if: False
        id: npm-cache
        uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-fe-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-fe-

      - name: Install dependencies
        run: |
          npm ci

      - name: Run Linting
        run: |
          npm run lint

  test:
    if: False
    runs-on: "ubuntu-22.04"

    steps:
      - name: Clone the repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm ci

      - name: Run Tests
        run: |
          npm run test

  build:
    if: False
    runs-on: "ubuntu-22.04"
    environment: dev
    needs: [ lint, test ]

    steps:
      - name: Clone the repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          # role-to-assume: github-action-user

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'

      - name: Build and push docker image to Amazon ECR
        run: |
          export ECR_REGISTRY=${{ vars.ECR_REGISTRY }}

          export FE_IMAGE_TAG=${{ github.sha }}
          docker-compose build movie-frontend
          docker-compose push movie-frontend

          export FE_IMAGE_TAG="latest"
          docker-compose build movie-frontend
          docker-compose push movie-frontend

  deploy:
    runs-on: "ubuntu-22.04"
    environment: dev
#    needs: build

    steps:
      - name: Clone the repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          # role-to-assume: github-action-user

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region ${{ secrets.AWS_DEFAULT_REGION }} --name ${{ vars.CLUSTER_NAME }}

      - name: Kustomize set image
        working-directory: frontend/k8s
        run: |
          kustomize edit set image frontend=${{ vars.ECR_REGISTRY }}/movie-frontend:latest

      - name: Deploy application to EKS cluster
        working-directory: frontend/k8s
        run: |
          kustomize build . | kubectl apply -f -

      - name: Verify Deployment Status
        run: |
          if kubectl rollout status deployment/frontend | grep -q 'successfully rolled out'; then
            echo "Deployment succeeded."
          else
            echo "Deployment failed."
            exit 1
          fi
